[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_STATIC_GENERATION = "true"

[[redirects]]
  from = "/api/auth/signout"
  to = "/auth/signin"
  status = 302

[[redirects]]
  from = "/api/auth/signout/*"
  to = "/auth/signin"
  status = 302

[[redirects]]
  from = "/api/auth/logout"
  to = "/auth/signin"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 