[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_DISABLE_STATIC_GENERATION = "true"
  NEXT_MINIMAL = "true"
  GENERATE_SOURCEMAP = "false"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**", ".next/**", "node_modules/**", "prisma/**", ".env"]
  excluded_files = ["*.md", "*.txt", "*.map", "*.lock", ".git/**", ".github/**", "node_modules/.cache/**"]
  external_node_modules = ["@prisma/client", "@supabase/supabase-js", "next-auth", "pg", "sharp", "next"]
  directory = "netlify/functions"
  timeout = 60
  max_bundle_size = "50mb"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 