[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# 클라이언트 사이드 라우팅을 위한 SPA 리디렉션
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = ["visitor", "user", "student"]}

# 보호된 경로에 대한 조건부 리디렉션
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = ["user", "student", "teacher", "admin"]}

[[redirects]]
  from = "/teacher/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = ["teacher", "admin"]}

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# 로그아웃 관련 리디렉션
[[redirects]]
  from = "/api/auth/signout"
  to = "/auth/signin"
  status = 302
  force = true

[[redirects]]
  from = "/api/auth/signout/*"
  to = "/auth/signin"
  status = 302
  force = true

[[redirects]]
  from = "/api/auth/logout"
  to = "/auth/signin"
  status = 302
  force = true 