[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# 개발 서버 설정
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# 함수 설정
[functions]
  node_bundler = "esbuild"

# 모든 경로를 index.html로 리디렉션하여 SPA 지원
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 