[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  from = "/auth/signin?callbackUrl=*"
  to = "/dashboard"
  status = 200
  force = false
  conditions = {Role = ["admin", "ADMIN"]}

# 모든 클라이언트 사이드 라우팅을 위한 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 